# Generated by Django 2.2 on 2021-04-21 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Ad_For_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_primary_key', models.CharField(default='none', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(default='none', max_length=100)),
                ('owner_mobile_number', models.CharField(default='none', max_length=100)),
                ('owner_email', models.CharField(max_length=50)),
                ('room_in_state', models.CharField(max_length=50)),
                ('room_in_city', models.CharField(max_length=50)),
                ('room_pin', models.CharField(max_length=10)),
                ('room_description', models.TextField(default='none')),
                ('room_rent', models.IntegerField()),
                ('room_desposite', models.IntegerField()),
                ('room_floor', models.SmallIntegerField()),
                ('total_floor', models.SmallIntegerField()),
                ('total_room', models.SmallIntegerField(default='1')),
                ('Bathroom', models.CharField(max_length=50)),
                ('House_Type', models.CharField(max_length=50)),
                ('Available', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Landmark', models.CharField(max_length=100)),
                ('full_location', models.CharField(default='NA', max_length=100)),
                ('near_by_hospital', models.CharField(default='none', max_length=500)),
                ('near_by_school', models.CharField(default='none', max_length=500)),
                ('near_by_company', models.CharField(default='none', max_length=500)),
                ('near_by_hotel', models.CharField(default='none', max_length=500)),
                ('near_by_shop', models.CharField(default='none', max_length=500)),
                ('location_map', models.CharField(default='none', max_length=500)),
                ('buildingName', models.CharField(default='none', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, upload_to='')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='RoomRent.Post_Ad_For_Room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_of_payment_sender', models.CharField(default='None', max_length=100)),
                ('email_of_payment_receiver', models.CharField(default='None', max_length=100)),
                ('name_of_receiver', models.CharField(default='None', max_length=100)),
                ('amount_to_pay', models.CharField(default='None', max_length=100)),
                ('payment_done_by_system_receiver', models.BooleanField(default=False)),
                ('message', models.CharField(default='None', max_length=100)),
                ('paymnet_method', models.CharField(default='PayPal', max_length=100)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='RoomRent.Post_Ad_For_Room')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiverEnd', models.IntegerField()),
                ('whole_msg_buffer', models.TextField(default=None)),
                ('sender_side_msg', models.TextField(blank=True, default='none')),
                ('msg_token', models.IntegerField(default=0)),
                ('session_chat_token', models.TextField(blank=True, default='none')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatWith', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerID', models.CharField(default='None', max_length=100)),
                ('renterName', models.CharField(default='None', max_length=100)),
                ('renterEmail', models.CharField(default='None', max_length=100)),
                ('ownerEmail', models.CharField(default='None', max_length=100)),
                ('monthlyDateOfRent', models.CharField(default='None', max_length=100)),
                ('startDateOfRent', models.CharField(default='None', max_length=100)),
                ('period', models.CharField(default='None', max_length=100)),
                ('endDateOfRent', models.CharField(default='None', max_length=100)),
                ('esignOwner', models.CharField(default='None', max_length=100)),
                ('esignRenter', models.CharField(default='None', max_length=100)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomID', to='RoomRent.Post_Ad_For_Room')),
            ],
        ),
    ]
