# Generated by Django 2.2 on 2021-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_done_by_system_receiver',
            new_name='payment_done',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymnet_method',
        ),
    ]
