# Generated by Django 2.2 on 2021-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRent', '0002_auto_20210427_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
