# Generated by Django 2.2 on 2021-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRent', '0003_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_ad_for_room',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=6),
        ),
    ]
